name: Ubuntu Tests (GCC-12+, Clang-17+)

on:
  push:
    branches: [ master, integration ]
  pull_request:
    branches: [ master, integration ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          # Ubuntu GCC configs
          - {
              name: "Ubuntu GCC 12",
              cc: "gcc-12",
              cxx: "g++-12"
            }
          - {
              name: "Ubuntu GCC 13",
              cc: "gcc-13",
              cxx: "g++-13"
            }
          - {
              name: "Ubuntu GCC 14",
              cc: "gcc-14",
              cxx: "g++-14"
            }
          # Ubuntu Clang configs
          - {
              name: "Ubuntu Clang 17",
              cc: "clang-17",
              cxx: "clang++-17"
            }
          - {
              name: "Ubuntu Clang 18",
              cc: "clang-18",
              cxx: "clang++-18"
            }
          - {
              name: "Ubuntu Clang 19",
              cc: "clang-19",
              cxx: "clang++-19"
            }

    steps:
    - uses: actions/checkout@v3

    - name: Setup CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: '3.31.5'

    - name: Install GCC 12 (Ubuntu)
      if: matrix.config.cc == 'gcc-12'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-12 g++-12

    - name: Install GCC 13 (Ubuntu)
      if: matrix.config.cc == 'gcc-13'
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-13 g++-13

    - name: Install GCC 14 (Ubuntu)
      if: matrix.config.cc == 'gcc-14'
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-14 g++-14

    - name: Install Clang 17 (Ubuntu)
      if: matrix.config.cc == 'clang-17'
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 17
        sudo apt-get install -y clang-17

    - name: Install Clang 18 (Ubuntu)
      if: matrix.config.cc == 'clang-18'
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 18
        sudo apt-get install -y clang-18

    - name: Install Clang 19 (Ubuntu)
      if: matrix.config.cc == 'clang-19'
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 19
        sudo apt-get install -y clang-19

    - name: Configure CMake
      shell: bash
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DCBOR_TAGS_BUILD_TESTS=ON \
          -DCMAKE_C_COMPILER=${{ matrix.config.cc }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}

    - name: Build
      shell: bash
      run: cmake --build build --config Release

    - name: Test
      working-directory: build
      shell: bash
      run: ctest -C Release --output-on-failure