name: Windows Tests (MSVC, Clang-CL)

on:
  push:
    branches: [ master, integration ]
  pull_request:
    branches: [ master, integration ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows MSVC",
              toolset: ""
            }
          - {
              name: "Windows Clang-CL",
              toolset: "ClangCL"
            }

    steps:
    - uses: actions/checkout@v6.0.2

    - name: Setup CMake
      uses: lukka/get-cmake@v4.3.2
      with:
        cmakeVersion: '3.31.5'
        useCloudCache: false

    - name: Configure CMake (Windows)
      shell: pwsh
      run: |
        $arguments = @(
          "-B", "build",
          "-G", "Visual Studio 17 2022",
          "-A", "x64",
          "-DCBOR_TAGS_BUILD_TESTS=ON"
        )
        if ("${{ matrix.config.toolset }}" -ne "") {
          $arguments += @("-T", "${{ matrix.config.toolset }}")
        }
        cmake @arguments

    - name: Build
      shell: bash
      run: cmake --build build --config Release

    - name: Test
      working-directory: build
      shell: bash
      run: ctest -C Release --output-on-failure
